# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=24)),
                ('description', models.TextField()),
                ('college', models.CharField(blank=True, max_length=32, null=True)),
                ('lesson', models.CharField(blank=True, max_length=32, null=True)),
                ('way', models.CharField(choices=[('a', 'Face to face'), ('b', 'express delivery')], max_length=1)),
                ('pictrue', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='sellBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=32, null=True)),
                ('lesson', models.CharField(blank=True, max_length=32, null=True)),
                ('way', models.CharField(blank=True, choices=[('a', 'Face to face'), ('b', 'express delivery')], max_length=1, null=True)),
                ('pictrue', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='campus',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='college',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='in_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='major',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='student_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sellbooks',
            name='on_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Users'),
        ),
        migrations.AddField(
            model_name='buybooks',
            name='buy_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Users'),
        ),
    ]
