# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171206_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, max_length=24, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('way', models.CharField(blank=True, choices=[('a', 'face to face'), ('b', 'express delivery'), ('c', 'both')], max_length=1, null=True)),
                ('pictrue', models.ImageField(blank=True, null=True, upload_to='')),
                ('state', models.CharField(blank=True, choices=[('a', 'on sale'), ('b', 'sold'), ('c', 'cancle')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('college', models.CharField(blank=True, max_length=32, null=True)),
                ('major', models.CharField(blank=True, max_length=32, null=True)),
                ('in_year', models.IntegerField(blank=True, default=0, null=True)),
                ('campus', models.CharField(blank=True, max_length=16, null=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('state', models.CharField(blank=True, choices=[('a', 'using'), ('b', 'closed')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buybooks',
            name='buy_by',
        ),
        migrations.RemoveField(
            model_name='sellbooks',
            name='on_sale',
        ),
        migrations.DeleteModel(
            name='buyBooks',
        ),
        migrations.DeleteModel(
            name='sellBooks',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
    ]
