# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171214_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
    ]
