# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171214_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'on sale'), (1, 'sold'), (2, 'cancle')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='way',
            field=models.IntegerField(blank=True, choices=[(0, 'face to face'), (1, 'express delivery'), (2, 'both')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'using'), (1, 'closed')], max_length=1, null=True),
        ),
    ]
