# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171214_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='way',
            field=models.IntegerField(blank=True, choices=[(0, 'cancle'), (1, 'face to face'), (2, 'express delivery'), (3, 'both')], max_length=1, null=True),
        ),
    ]
