# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20171214_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='way',
            field=models.IntegerField(blank=True, choices=[(0, 'cancle'), (1, 'face to face'), (2, 'express delivery'), (3, 'both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'using'), (1, 'closed')], max_length=10, null=True),
        ),
    ]
