# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_uploadobj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadObj',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pictrue',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'on sale'), (1, 'sold'), (2, 'cancle')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='way',
            field=models.IntegerField(blank=True, choices=[(0, 'cancle'), (1, 'face to face'), (2, 'express delivery'), (3, 'both')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'using'), (1, 'closed')], null=True),
        ),
    ]
