# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20171216_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='way',
            field=models.IntegerField(blank=True, choices=[(0, 'cancle'), (1, '面交'), (2, '快递'), (3, '面交或快递')], null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(blank=True, default=3, max_length=10, null=True),
        ),
    ]
