# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20171216_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='book_name',
            new_name='book_id',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='comment',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'using'), (1, 'closed')], default=0, null=True),
        ),
    ]
