# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20171216_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relation',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
