# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20171216_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
