# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20171216_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tobuyer_comment',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
