# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_order_tobuyer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
