# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20171217_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='c_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tobuyer_c_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'buy'), (1, 'cancle')], default=0, null=True),
        ),
    ]
