# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20171217_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
