# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20171217_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
