# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20171218_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
