# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20171218_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bookname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='picture',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'buy'), (1, 'cancle')], default=0, null=True),
        ),
    ]
